# Generated by Django 4.1.2 on 2025-10-27 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_user_company"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RecuperarSenha",
            new_name="RecoveryPassword",
        ),
    ]
