# Generated by Django 4.1.2 on 2025-10-27 22:18

import access.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0003_rename_recuperarsenha_recoverypassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="expires_at",
            field=models.DateTimeField(default=access.models.default_expiration),
        ),
        migrations.AlterField(
            model_name="token",
            name="iat",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
