# Generated by Django 4.1.2 on 2025-11-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_filecandidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
