# Generated by Django 4.1.2 on 2025-11-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_alter_candidate_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
