# Generated by Django 4.1.2 on 2025-12-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_alter_candidate_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="profile_resume",
            field=models.TextField(blank=True, null=True),
        ),
    ]
