# Generated by Django 4.1.2 on 2025-10-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("msg", models.TextField(null=True)),
                (
                    "typed",
                    models.CharField(
                        choices=[
                            ("Warning", "Warning"),
                            ("Print", "Print"),
                            ("Error", "Error"),
                            ("Confirm", "Confirm"),
                            ("OK", "OK"),
                        ],
                        default="OK",
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestDebugLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.TextField()),
                ("full_path", models.TextField()),
                ("user_str", models.CharField(blank=True, max_length=255, null=True)),
                ("remote_addr", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referer", models.TextField(blank=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("post_data", models.JSONField(blank=True, default=dict)),
                ("body_content", models.TextField(blank=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("content_length", models.CharField(blank=True, max_length=20)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("reason_phrase", models.CharField(blank=True, max_length=100)),
                ("response_content_type", models.CharField(blank=True, max_length=100)),
                ("response_content", models.TextField(blank=True)),
                ("exception_type", models.CharField(blank=True, max_length=100)),
                ("exception_message", models.TextField(blank=True)),
                ("exception_traceback", models.TextField(blank=True)),
                ("processing_time_ms", models.FloatField(blank=True, null=True)),
                ("log_level", models.CharField(default="INFO", max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="access.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="requestdebuglog",
            index=models.Index(
                fields=["timestamp"], name="logs_reques_timesta_40e07f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestdebuglog",
            index=models.Index(
                fields=["status_code"], name="logs_reques_status__ce158f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestdebuglog",
            index=models.Index(fields=["method"], name="logs_reques_method_e1dd50_idx"),
        ),
        migrations.AddIndex(
            model_name="requestdebuglog",
            index=models.Index(
                fields=["log_level"], name="logs_reques_log_lev_45bbce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestdebuglog",
            index=models.Index(fields=["user"], name="logs_reques_user_id_8136c2_idx"),
        ),
    ]
