# Generated by Django 4.1.2 on 2025-10-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("access", "0002_user_company"),
        ("company", "0002_candidate_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ask", models.TextField(verbose_name="Pergunta")),
                (
                    "answer",
                    models.TextField(blank=True, null=True, verbose_name="Resposta"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="access.user",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Query",
                "verbose_name_plural": "Queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Indication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indications",
                        to="company.candidate",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indications",
                        to="ai.queries",
                        verbose_name="Query",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicação",
                "verbose_name_plural": "Indicações",
                "ordering": ["-created_at"],
            },
        ),
    ]
