# Generated by Django 4.1.2 on 2025-11-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0004_alter_token_expires_at_alter_token_iat"),
        ("ai", "0002_alter_queries_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queries",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queries",
                to="access.user",
                verbose_name="Usuário",
            ),
        ),
    ]
